language: generic
services:
    - docker
env:
    global:
        - ROS_REPO=ros
    matrix:
        - ROS_DISTRO="kinetic"
        - ROS_DISTRO="melodic"
install:
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
    - .industrial_ci/travis.sh

