<?xml version="1.0"?>
<package format="3">
  <name>pointcloud_test_publisher</name>
  <version>0.1.0</version>
  <description>Simple PointCloud publisher for testing the Potree RViz plugin.</description>

  <maintainer email="user@example.com">Test Maintainer</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
